package com.android.internal.telephony;

import android.location.OplusLbsCommonConstant;
import android.os.OplusPropertyList;
import android.os.SystemProperties;
import android.telephony.Rlog;
import com.oplus.content.IOplusFeatureConfigList;
/* loaded from: classes4.dex */
public class OplusFeature {
    public static final boolean FEATURE_NW_RADIO_HOOK;
    public static final boolean OPLUS_FEATURE_1X_BSR_DDS_SWITCH;
    public static final boolean OPLUS_FEATURE_5G_BAND_CFG;
    public static final boolean OPLUS_FEATURE_AUTO_ANSWER = true;
    public static final boolean OPLUS_FEATURE_CALL_PRESENTATION_MAPPING = true;
    public static final boolean OPLUS_FEATURE_COMM_PROXIMITY = true;
    public static final boolean OPLUS_FEATURE_CTIMSSMS_AUTOREG = true;
    public static final boolean OPLUS_FEATURE_DATA_MTU = true;
    public static final boolean OPLUS_FEATURE_ENGNW_STS_INTERFACE_SUPPORT;
    public static final boolean OPLUS_FEATURE_FEMTOCELL_UI;
    public static final boolean OPLUS_FEATURE_FIVE_SIGNAL_BAR;
    public static final boolean OPLUS_FEATURE_FIX_DUPLICATEDSMS;
    public static final boolean OPLUS_FEATURE_IGNORE_GOOGLE_ORIGINAL_NOTIFICATION_PS_CS = true;
    public static final boolean OPLUS_FEATURE_IMS_GUARD;
    public static final boolean OPLUS_FEATURE_NW_DATA_DOMESTIC_ROAMING = true;
    public static final boolean OPLUS_FEATURE_NW_DATA_HONGBAO = true;
    public static final boolean OPLUS_FEATURE_NW_DATA_ROAMING_ENABLED = true;
    public static final boolean OPLUS_FEATURE_NW_DATA_TELSTRA = true;
    public static final boolean OPLUS_FEATURE_NW_DATA_VSIM = true;
    public static final boolean OPLUS_FEATURE_OFFHOTSPOT_SIMREFRESH;
    public static final boolean OPLUS_FEATURE_PUT_CARD_TYPE_TO_DB = true;
    public static final boolean OPLUS_FEATURE_RADIO_LCMHOPPING_URC;
    public static final boolean OPLUS_FEATURE_RUS_TELEPHONY = true;
    public static final boolean OPLUS_FEATURE_SAR_BACKOFF_DISABLED;
    public static final boolean OPLUS_FEATURE_SHOW_IMS_CONFERENCE_LIST_WITHOUT_CEP_CONFIG = true;
    public static final boolean OPLUS_FEATURE_SIM_CMCC_AUTO_REG = true;
    public static final boolean OPLUS_FEATURE_SIM_HOTSWAP = true;
    public static final boolean OPLUS_FEATURE_SIM_LOCALE = true;
    public static final boolean OPLUS_FEATURE_SIM_REGION = true;
    public static final boolean OPLUS_FEATURE_SMSGSM8IT_ENABLE = true;
    public static final boolean OPLUS_FEATURE_SOFT_SIM = true;
    public static final boolean OPLUS_FEATURE_SUPPORT_ROMOLDFUNC = true;
    public static final boolean OPLUS_FEATURE_TEMP_DDSSWITCH = true;
    public static final boolean OPLUS_FEATURE_USS_DATA_ERROR_MESSAGE;
    public static final boolean OPLUS_FEATURE_USS_ROAMING_ALERT;
    public static final boolean OPLUS_FEATURE_USS_ROAMING_REDUCTION;
    public static final boolean OPLUS_FEATURE_USS_ROAMING_SUPPORT;
    public static final boolean OPLUS_FEATURE_UST_5G_UC;
    public static final boolean OPLUS_FEATURE_UST_ADB_SET_SVN;
    public static final boolean OPLUS_FEATURE_UST_CARRIER_CONFIG;
    public static final boolean OPLUS_FEATURE_UST_DATA_ALWAYS_ON;
    public static final boolean OPLUS_FEATURE_UST_DATA_ROAMING_POPUP;
    public static final boolean OPLUS_FEATURE_UST_ECHOLOCATE;
    public static final boolean OPLUS_FEATURE_UST_NONE_SIM_ECC;
    public static final boolean OPLUS_FEATURE_UST_SIMLOCK;
    public static final boolean OPLUS_FEATURE_UST_SMART_WIFICALLING;
    public static final boolean OPLUS_FEATURE_UST_STIR;
    public static final boolean OPLUS_FEATURE_UST_TOAST;
    public static final boolean OPLUS_FEATURE_UST_UA;
    public static final boolean OPLUS_FEATURE_UST_UNIFIED_DEVICE;
    public static final boolean OPLUS_FEATURE_UST_USKU_DEVICE;
    public static final boolean OPLUS_FEATURE_USV_EMERGENCY_CALL;
    public static final boolean OPLUS_FEATURE_USV_OMA_APN;
    public static final boolean OPLUS_FEATURE_USV_PCO;
    public static final boolean OPLUS_FEATURE_VOICE_DTMF;
    public static final boolean OPLUS_FEATURE_WAPPUSH_ENABLE;
    public static final boolean OPLUS_FEATURE_WIFI_DATA_CONTROL = true;
    private static final boolean isQcomPlatform = SystemProperties.get("ro.boot.hardware", "unknow").toLowerCase().startsWith(OplusLbsCommonConstant.QCOM_PLATFORM);
    private static final boolean isMTKPlatform = SystemProperties.get("ro.boot.hardware", "unknow").toLowerCase().startsWith("mt");
    private static final boolean isUSSUnifyDevice = SystemProperties.get(OplusPropertyList.PROPETY_OPLUS_OPCARRIER_ID).equals("sprint");
    private static final boolean isUSTUnifyDevice = SystemProperties.get(OplusPropertyList.PROPETY_OPLUS_OPCARRIER_ID).equals("tmo");
    public static final boolean OPLUS_FEATURE_SIGNAL_SMOOTH = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SIGNAL_SMOOTH_DISABLED);
    public static final boolean OPLUS_FEATURE_NR_ICON_OPTIMIZED = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_NR_ICON_OPTIMIZED_ENABLED);
    public static final boolean OPLUS_FEATURE_SUPPORT_DUAL_NR = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SUPPORT_DUAL_NR);
    public static final boolean OPLUS_FEATURE_LTE_INSTEND_OF_CA = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_LTE_INSTEND_OF_CA);
    public static final boolean OPLUS_FEATURE_LIGHT_SMART5G = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_LIGHT_SMART5G_ENABLED);
    public static final boolean OPLUS_FEATURE_SMART5G_SA = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_SA_ENABLED);
    public static final boolean OPLUS_FEATURE_SMART5G_EXP_CFG = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_EXP_CFG);
    public static final boolean OPLUS_FEATURE_SMART5G_SP_REGION_DISABLE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_SP_REGION_DISABLE);
    public static final boolean OPLUS_FEATURE_DUAL_SIMS_SMART5G_ENABLED = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DUAL_SIMS_SMART5G_ENABLED);
    public static final boolean OPLUS_FEATURE_SMART5G_RTT_CHECK = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_RTT_CHECK);
    public static final boolean OPLUS_FEATURE_SMART5G_NR_SIGNAL_CHECK = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_NR_SIGNAL_CHECK);
    public static final boolean OPLUS_FEATURE_SMART5G_GMAE_LATENCY_CHECK = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_GAME_LATENCY_CHECK);
    public static final boolean OPLUS_FEATURE_SMART5G_NR_RTT_CHECK = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_NR_RTT_CHECK);
    public static final boolean OPLUS_FEATURE_SMART5G_RTT_CHECK_SA = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_RTT_CHECK_SA);
    public static final boolean OPLUS_FEATURE_SMART5G_GMAE_LIST_DEPRIO_SA = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_GMAE_LIST_DEPRIO_SA);
    public static final boolean OPLUS_FEATURE_SMART5G_GAME_LTE_PREFER = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_GAME_LTE_PREFER);
    public static final boolean OPLUS_FEATURE_SMART5G_SA_ENVIRONMENT_GAME_LTE_PREFER = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_SA_ENVIRONMENT_GAME_LTE_PREFER);
    public static final boolean OPLUS_FEATURE_SMART5G_THERMAL_NR_DEPRIO = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_THERMAL_NR_DEPRIO);
    public static final boolean OPLUS_FEATURE_SMART5G_HOTSPOT_ENABLE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_HOTSPOT_ENABLE);
    public static final boolean OPLUS_FEATURE_SMART5G_NR_S_DROP_CTRL = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_NR_S_DROP_CTRL);
    public static final boolean OPLUS_FEATURE_SMART5G_THERMAL_NR_S_DROP = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_THERMAL_NR_S_DROP);
    public static final boolean OPLUS_FEATURE_SMART5G_SPEEDBASED_NR_S_DROP = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_SPEEDBASED_NR_S_DROP);
    public static final boolean OPLUS_FEATURE_SMART5G_FENCE_SA_DATA_SLOW = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMART5G_FENCE_SA_DATA_SLOW);
    public static final boolean OPLUS_FEATURE_ECC_CSFB_UPDATE_RAT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_ECC_CSFB_UPDATE_RAT);
    public static final boolean OPLUS_FEATURE_IGNORE_RETRICTED_ENABLED = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_IGNORE_RETRICTED_ENABLED);
    public static final boolean OPLUS_FEATURE_DISABLE_AUTO_NETWORK_SELECT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DISABLE_AUTO_NETWORK_SELECT);
    public static final boolean OPLUS_FEATURE_DISPLAY_PLMN_SPN = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DISPLAY_PLMN_SPN);
    public static final boolean OPLUS_FEATURE_LOC_CONTROL_SWITCH = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_LOC_CONTROL_SWITCH);
    public static final boolean OPLUS_FEATURE_SHOW_NR5G_MODE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SHOW_NR5G_MODE);
    public static final boolean OPLUS_FEATURE_DISABLE_NR5G_CAUSE_5G_DUMP = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DISABLE_NR5G_CAUSE_5G_DUMP);
    public static final boolean OPLUS_FEATURE_NR_NRCA_RUS_CONTROL = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_NR_NRCA_RUS_CONTROL);
    public static final boolean OPLUS_FEATURE_NR_BWP_RUS_CONTROL = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_NR_BWP_RUS_CONTROL);
    public static final boolean OPLUS_FEATURE_NR_ALWAYS_SA_PRE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_NR_ALWAYS_SA_PRE);
    public static final boolean OPLUS_FEATURE_SA_RAT_CONTROL = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SA_RAT_CONTROL);
    public static final boolean OPLUS_FEATURE_SA_PINGPONG_CONTROL_EABLED = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SA_PINGPONG_CONTROL_DISABLED);
    public static final boolean OPLUS_FEATURE_SA_CALL_CONTROL_EABLED = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SA_CALL_CONTROL_DISABLED);
    public static final boolean OPLUS_FEATURE_SA_TAC_CONTROL = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SA_TAC_CONTROL);
    public static final boolean OPLUS_FEATURE_SA_APM_CONTROL = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SA_APM_CONTROL);
    public static final boolean OPLUS_FEATURE_SA_IMS_CONTROL = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SA_IMS_CONTROL_DISABLED);
    public static final boolean OPLUS_FEATURE_SA_TIME_CONTROL = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SA_TIME_CONTROL_DISABLED);
    public static final boolean OPLUS_FEATURE_SA_REG_TIMEOUT_CONTROL_ENABLED = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SA_REG_TIMEOUT_CONTROL_ENABLED);
    public static final boolean OPLUS_FEATURE_SA_SCREEN_OFF_DISABLE_SA_ENABLED = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SA_SCREEN_OFF_DISABLE_SA_ENABLED);
    public static final boolean OPLUS_FEATURE_SA_DATA_CALL_CONTROL_DISABLED = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SA_DATA_CALL_CONTROL_DISABLED);
    public static final boolean OPLUS_FEATURE_SA_BACKOFF_SA_CAUSE_NETWORK_REJECT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SA_BACKOFF_SA_CAUSE_NETWORK_REJECT);
    public static final boolean OPLUS_FEATURE_DISABLE_ALL_SA_BACKOFF = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DISABLE_ALL_SA_BACKOFF);
    public static final boolean OPLUS_FEATURE_FAST_DORMANCY = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_FAST_DORMANCY);
    public static final boolean OPLUS_FEATURE_ENDC_NR_SIGNAL_OPTIMIZATION = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_ENDC_NR_SIGNAL_OPTIMIZATION);
    public static final boolean OPLUS_FEATURE_JP_SIGNAL_STRENGTH = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_JP_SIGNAL_STRENGTH);
    public static final boolean OPLUS_FEATURE_DATA_DYNAMIC_ENABLE = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DATA_DYNAMIC_ENABLE);
    public static final boolean OPLUS_FEATURE_FETCH_NUMBER_COUNTRY_NAME = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_FETCH_NUMBER_COUNTRY_NAME);
    public static final boolean OPLUS_FEATURE_CUSTOM_PLMN_FOR_SPECIAL_OPERATOR = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_CUSTOM_PLMN_FOR_SPECIAL_OPERATOR);
    public static final boolean OPLUS_FEATURE_SIM_NAME_LENGTH_DEFAULT_TEN = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SIM_NAME_LENGTH_DEFAULT_TEN);
    public static final boolean OPLUS_FEATURE_MIX_SIM_NAME_LEN_DEFAULT_TEN = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_MIX_SIM_NAME_LEN_DEFAULT_TEN);
    public static final boolean OPLUS_FEATURE_PROCESS_REGION_CHANGE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_PROCESS_REGION_CHANGE);
    public static final boolean OPLUS_FEATURE_SET_POL_ENTRY_COMPLETE_WITH_LAST_ITEM = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SET_POL_ENTRY_COMPLETE_WITH_LAST_ITEM);
    public static final boolean OPLUS_FEATURE_SUPPORT_ESIM = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SHOW_ESIM_ENGINEERMODE_ENABLED);
    public static final boolean OPLUS_FEATURE_5G_SUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_5G_SUPPORT);
    public static final boolean OPLUS_FEATURE_LOCAL_RELEASE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_LOCAL_RELEASE);
    public static final boolean OPLUS_FEATURE_EXP_NOTSHOW_STK_BOOTWIZARD = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_EXP_NOTSHOW_STK_BOOTWIZARD);
    public static final boolean OPLUS_FEATURE_ENABLE_OEM_LOG = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_ENABLE_OEM_LOG);
    public static final boolean OPLUS_FEATURE_CALL_FORWARDING_NUM_EXT_DISABLED = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_CALL_FORWARDING_NUM_EXT_DISABLED);
    public static final boolean OPLUS_FEATURE_ENABLE_DIALING_NULBER_CHECK = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_ENABLE_DIALING_NULBER_CHECK);
    public static final boolean OPLUS_FEATURE_DISABLE_KEYLOG_PRINT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DISABLE_KEYLOG_PRINT);
    public static final boolean OPLUS_FEATURE_ENABLE_TELCEL_COSTOMIZE_NAME = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_ENABLE_TELCEL_COSTOMIZE_NAME);
    public static final boolean OPLUS_FEATURE_5G_ICON_JP_REQUIREMENT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_5G_ICON_JP_REQUIREMENT);
    public static final boolean OPLUS_FEATURE_SUBINFO_MCCMNC_ADVANCE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SUBINFO_MCCMNC_ADVANCE);
    public static final boolean OPLUS_FEATURE_SPN_AS_DISPLAYNAME = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SPN_AS_DISPLAYNAME);
    public static final boolean OPLUS_FEATURE_SA_MODE_ROAMING_CONTROL = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SA_MODE_ROAMING_CONTROL);
    public static final boolean OPLUS_FEATURE_ENABLE_SA_WEAK_SIGNAL_BACKOFF = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_ENABLE_SA_WEAK_SIGNAL_BACKOFF);
    public static final boolean OPLUS_FEATURE_NETWORK_FENCE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_NETWORK_FENCE);
    public static final boolean OPLUS_FEATURE_ULTIMATE_FIVE_G_SUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_ULTIMATE_FIVE_G_SUPPORT);
    public static final boolean OPLUS_FEATURE_DIAGNOSE_PARSE_NR_CELL_SUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DIAGNOSE_PARSE_NR_CELL_SUPPORT);
    public static final boolean OPLUS_FEATURE_RECOVERY_NRMODE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_RECOVERY_NRMODE);
    public static final boolean OPLUS_FEATURE_SIM_CONTACTS_SUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SIM_CONTACTS_SUPPORT);
    public static final boolean OPLUS_FEATURE_POLICY_SALEMODE = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_POLICY_SALEMODE_DISABLED);
    public static final boolean OPLUS_FEATURE_CDMACW_FILTER = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_CDMACW_FILTER_DISABLED);
    public static final boolean OPLUS_FEATURE_ECC_SOLUTION = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_ECC_SOLUTION_DISABLED);
    public static final boolean OPLUS_FEATURE_1X_INCALL_MMI_CODE = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_1X_INCALL_MMI_CODE_DISABLED);
    public static final boolean OPLUS_FEATURE_SIP491_RESUME_FAILURE = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SIP491_RESUME_FAILURE_DISABLED);
    public static final boolean OPLUS_FEATURE_GAMESPACE_MT_OPTIMIZATION = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_GAMESPACE_MT_OPTIMIZATION);
    public static final boolean OPLUS_FEATURE_SHOW_HD_PLUS = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SHOW_HD_PLUS);
    public static final boolean OPLUS_FEATURE_IGNORE_SIM_VM_NUMBER = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_IGNORE_SIM_VM_NUMBER);
    public static final boolean OPLUS_FEATURE_SWITCH_ECT = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SWITCH_ECT);
    public static final boolean OPLUS_FEATURE_WFC_DISABLE_NRSA = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_WFC_DISABLE_NRSA);
    public static final boolean OPLUS_FEATURE_AUTO_DISABLE_SMART_WFC_SA_CONTROLLER = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_AUTO_DISABLE_SMART_WFC_SA_CONTROLLER);
    public static final boolean OPLUS_FEATURE_AUTO_ENABLE_SMART_WFC_SA_CONTROLLER = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_AUTO_ENABLE_SMART_WFC_SA_CONTROLLER);
    public static final boolean OPLUS_FEATURE_VONR_SWITCH_ENABLED = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_VONR_SWITCH_ENABLED);
    public static final boolean OPLUS_FEATURE_VONR_CITY_CONTROL = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_VONR_CITY_CONTROL);
    public static final boolean OPLUS_FEATURE_CLIR_DEFAULT_SUPPRESSION = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_CLIR_DEFAULT_SUPPRESSION);
    public static final boolean OPLUS_FEATURE_STS_AUTO_ANSWER_SUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_STS_AUTO_ANSWER_SUPPORT);
    public static final boolean OPLUS_FEATURE_CALL_RECOVERY_DISABLED = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.OPLUS_FEATURE_CALL_RECOVERY_DISABLED);
    public static final boolean OPLUS_FEATURE_SIGNAL_RECOVERY = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SIGNAL_RECOVERY);
    public static final boolean OPLUS_FEATURE_SILENT_REDIAL_SUPPORTED = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SILENT_REDIAL_SUPPORTED);
    public static final boolean OPLUS_FEATURE_NW_DATA_FAST_DORMANCY = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_NW_DATA_FAST_DORMANCY_DISABLED);
    public static final boolean OPLUS_FEATURE_NTP_PREFERRED = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_NTP_PREFERRED);
    public static final boolean OPLUS_FEATURE_FAST_RECOVERY = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_NW_DATA_FAST_RECOVERY);
    public static final boolean OPLUS_FEATURE_APTG_FORCE_ENABLE_ROAMING = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_APTG_FORCE_ENABLE_ROAMING);
    public static final boolean OPLUS_FEATURE_MAX_THREE_PDNS = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_MAX_THREE_PDNS);
    public static final boolean OPLUS_FEATURE_DATA_AVOID_DATA_ICON = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DATA_AVOID_DATA_ICON_DISABLED);
    public static final boolean OPLUS_FEATURE_ROAMING_DYNAMIC_DUN_APN = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_ROAMING_DYNAMIC_DUN_APN);
    public static final boolean OPLUS_FEATURE_DATA_DEFAULT_AS_DUN_APN = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DATA_DEFAULT_AS_DUN_APN_DISABLED);
    public static final boolean OPLUS_FEATURE_NOTIFY_DATA_CONNECTION = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_NOTIFY_DATA_CONNECTION);
    public static final boolean OPLUS_FEATURE_VICE_CARD_GAME_MODE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_VICE_CARD_GAME_MODE);
    public static final boolean OPLUS_FEATURE_GEOIPTIME = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_GEOIPTIME);
    public static final boolean OPLUS_FEATURE_DISABLE_NW_LIMIT_NOTIFY = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DISABLE_NW_LIMIT_NOTIFY);
    public static final boolean OPLUS_FEATURE_UST_DATA_DEVICE_REPORTING = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_UST_DATA_DEVICE_REPORTING);
    public static final boolean OPLUS_FEATURE_SCENE_MODE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SCENE_MODE);
    public static final boolean OPLUS_FEATURE_MEETING_OPITMIZ = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_MEETING_OPITMIZ);
    public static final boolean OPLUS_FEATURE_DATA_BLOCK_NONDDS_IMS_PAKG = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DATA_BLOCK_NONDDS_IMS_PAKG);
    public static final boolean OPLUS_FEATURE_DATA_DNS_SPEED_UP = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DATA_DNS_SPEED_UP);
    public static final boolean OPLUS_FEATURE_APN_RUS_UPDATE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_APN_RUS_UPDATE);
    public static final boolean OPLUS_FEATURE_SA_DATA_RECOVERY = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SA_DATA_RECOVERY);
    public static final boolean OPLUS_FEATURE_INCREASE_TCP_SYNC_RETRIES = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.OPLUS_FEATURE_INCREASE_TCP_SYNC_RETRIES);
    public static final boolean OPLUS_FEATURE_GAME_IMS_REG = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_GAME_IMS_REG);
    public static final boolean OPLUS_FEATURE_GAME_BACKOFF_SA = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_GAME_BACKOFF_SA);
    public static final boolean OPLUS_FEATURE_DITO_CT_ATUO_IMS_REG = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DITO_CT_ATUO_IMS_REG);
    public static final boolean OPLUS_FEATURE_SMS_7BIT16BIT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMS_7BIT16BIT);
    public static final boolean OPLUS_FEATURE_PULL_WIFI_CELL = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_PULL_WIFI_CELL);
    public static final boolean OPLUS_FEATURE_DDS_SWITCH = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DDS_SWITCH);
    public static final boolean OPLUS_FEATURE_LOG_GAME_ERR = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_LOG_GAME_ERR);
    public static final boolean OPLUS_FEATURE_LOG_GAME_PAGING = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_LOG_GAME_PAGING);
    public static final boolean OPLUS_FEATURE_FIND_PHONE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SMS_FIND_PHONE);
    public static final boolean OPLUS_FEATURE_MMS_NOT_ALLOW_INTERNET = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_MMS_NOT_ALLOW_INTERNET);
    public static final boolean OPLUS_FEATURE_GOOGLE_MESSAGE_CONFIG = !OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_GOOGLE_MESSAGE_CONFIG_ENABLE);
    public static final boolean OPLUS_FEATURE_TELEPHONY_DISABLED_RUS = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_TELEPHONY_DISABLED_RUS);
    public static final boolean OPLUS_FEATURE_TELEPHONY_DISABLED_KEY_LOG = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_TELEPHONY_DISABLED_KEY_LOG);
    public static final boolean OPLUS_FEATURE_DELAY_SMS_WHEN_BROADCASTING = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DELAY_SMS_WHEN_BROADCASTING);
    public static final boolean OPLUS_FEATURE_DELAY_AML_SMS = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DELAY_AML_SMS);
    public static final boolean OPLUS_FEATURE_CMCC_DM_SWITCH = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_CMCC_DM);
    public static final boolean OPLUS_FEATURE_EXP_OPERATOR_SWITCH_ENABLE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_EXP_OPERATOR_SWITCH_ENABLE);
    public static final boolean OPLUS_FEATURE_RETRY_OPEN_CHANNEL_FOR_TW = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_RETRY_OPEN_CHANNEL_FOR_TW);
    public static final boolean OPLUS_FEATURE_SUPPORT_SIM_LOCK_STATE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SUPPORT_SIM_LOCK_STATE);
    public static final boolean OPLUS_FEATURE_DISALBE_FIRST_FEATURE_LOAD = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DISABLE_FIRST_FEATURE_LOAD);
    public static final boolean OPLUS_FEATURE_SIM_DETECT_STATUS_CHECK_SUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SIM_DETECT_STATUS_CHECK_SUPPORT);
    public static final boolean OPLUS_FEATURE_SIM2_DETECT_NOT_SUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SIM2_DETECT_NOT_SUPPORT);
    public static final boolean OPLUS_FEATURE_SUPPORT_SIM_DISPLAY_NAME = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SUPPORT_SIM_DISPLAY_NAME);
    public static final boolean OPLUS_FEATURE_ONLY_GET_SIM_MSISDN = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_ONLY_GET_SIM_MSISDN);
    public static final boolean OPLUS_FEATURE_COMM_AOL = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_MOTOR_DAT_ENABLED);
    public static final boolean OPLUS_FEATURE_RF_SAR_EARPIECE_DETECT_SUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SAR_EARPIECE_DETECT_SUPPORT);
    public static final boolean OPLUS_FEATURE_RF_SAR_FCC_DETECT_SUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SAR_FCC_DETECT_SUPPORT);
    public static final boolean OPLUS_FEATURE_RF_SAR_AIRINTERFACE_DETECT_NOTSUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SAR_AIRINTERFACE_DETECT_NOTSUPPORT);
    public static final boolean OPLUS_FEATURE_RF_SAR_BT_DETECT_SUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SAR_BT_DETECT_SUPPORT);
    public static final boolean OPLUS_FEATURE_RF_SAR_SENSOR = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SAR_ENABLE);
    public static final boolean OPLUS_FEATURE_FORCE_FCC_SAR_REGION = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_FORCE_FCC_SAR_REGION);
    public static final boolean OPLUS_FEATURE_SUPPORT_FCC_SAR_REGION = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SUPPORT_FCC_SAR_REGION);
    public static final boolean FEATURE_RF_BAR_CELL = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_RF_BAR_CELL);
    public static final boolean OPLUS_FEATURE_NO_BAND_SELECTIONS = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_NO_BAND_SELECTIONS);
    public static final boolean OPLUS_FEATURE_SET_RAT_NO_DELAY = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SET_RAT_NO_DELAY);
    public static final boolean OPLUS_FEATURE_AOL_SCENE_TO_MODEM = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_AOL_SCENE_TO_MODEM);
    public static final boolean OPLUS_FEATURE_USB_SCENES_GAMES_OP = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_USB_SCENES_GAMES_OP_CONFIG);
    public static final boolean OPLUS_FEATURE_SAR_VIA_STS_SUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_RADIO_SAR_VIA_STS_SUPPORT);
    public static final boolean OPLUS_FEATURE_RF_HW_MIPI_FAIL_SUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_HW_MIPI_FAIL_SUPPORT);
    public static final boolean FEATURE_NWPOWER_POWER_RECOVERY_SWITCH_ENABLE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_NWPOWER_POWER_RECOVERY_SWITCH_ENABLE);
    public static final boolean FEATURE_NW_NEC = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_RADIO_HEALTH_SERVICE_SUPPORT);
    public static final boolean OPLUS_FEATURE_ELEV_AUTOMATION = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_ELEV_AUTOMATION);
    public static final boolean OPLUS_FEATURE_ELEV_GW_NDDS = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_ELEV_GW_NDDS);
    public static final boolean OPLUS_FEATURE_USV_UA = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_USV_UA);
    public static final boolean OPLUS_FEATURE_USV_UWICON = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_USV_UWICON);

    static {
        boolean z = true;
        boolean z2 = isQcomPlatform;
        OPLUS_FEATURE_WAPPUSH_ENABLE = z2;
        OPLUS_FEATURE_FIX_DUPLICATEDSMS = z2;
        boolean hasFeature = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_RADIO_HOOK);
        FEATURE_NW_RADIO_HOOK = hasFeature;
        boolean hasFeature2 = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_UST_USKU_DEVICE);
        OPLUS_FEATURE_UST_USKU_DEVICE = hasFeature2;
        OPLUS_FEATURE_UST_NONE_SIM_ECC = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_UST_NONE_SIM_ECC) && (isUSTUnifyDevice || hasFeature2);
        OPLUS_FEATURE_UST_DATA_ROAMING_POPUP = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_UST_DATA_ROAMING_POPUP);
        OPLUS_FEATURE_UST_TOAST = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_UST_TOAST) && (isUSTUnifyDevice || hasFeature2);
        OPLUS_FEATURE_UST_UA = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.OPLUS_FEATURE_UST_UA) && (isUSTUnifyDevice || hasFeature2);
        OPLUS_FEATURE_UST_STIR = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_UST_STIR) && (isUSTUnifyDevice || hasFeature2);
        OPLUS_FEATURE_FEMTOCELL_UI = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_FEMTOCELL_UI);
        OPLUS_FEATURE_USV_EMERGENCY_CALL = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_USV_EMERGENCY_CALL);
        OPLUS_FEATURE_USS_ROAMING_REDUCTION = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_USS_ROAMING_REDUCTION) && isUSSUnifyDevice;
        OPLUS_FEATURE_USS_ROAMING_ALERT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_USS_ROAMING_ALERT) && isUSSUnifyDevice;
        OPLUS_FEATURE_USS_DATA_ERROR_MESSAGE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_USS_DATA_ERROR_MESSAGE) && isUSSUnifyDevice;
        OPLUS_FEATURE_USS_ROAMING_SUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_USS_ROAMING_SUPPORT) && isUSSUnifyDevice;
        OPLUS_FEATURE_IMS_GUARD = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_IMS_GUARD);
        OPLUS_FEATURE_UST_UNIFIED_DEVICE = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_UST_UNIFY_DEVICE);
        OPLUS_FEATURE_UST_CARRIER_CONFIG = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_UST_CARRIER_CONFIG) && (isUSTUnifyDevice || hasFeature2);
        OPLUS_FEATURE_USV_OMA_APN = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_USV_OMA_APN);
        OPLUS_FEATURE_UST_DATA_ALWAYS_ON = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_UST_DATA_ALWAYS_ON) && (isUSTUnifyDevice || hasFeature2);
        OPLUS_FEATURE_UST_SIMLOCK = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_UST_SIMLOCK) && isUSTUnifyDevice;
        OPLUS_FEATURE_VOICE_DTMF = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_VOICE_DTMF);
        OPLUS_FEATURE_USV_PCO = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_USV_PCO);
        OPLUS_FEATURE_UST_SMART_WIFICALLING = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_UST_SMART_WIFICALLING) && (isUSTUnifyDevice || hasFeature2);
        if (!OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_UST_ECHOLOCATE) || (!isUSTUnifyDevice && !hasFeature2)) {
            z = false;
        }
        OPLUS_FEATURE_UST_ECHOLOCATE = z;
        OPLUS_FEATURE_ENGNW_STS_INTERFACE_SUPPORT = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_RADIO_ENGNW_STS_INTERFACE_SUPPORT);
        OPLUS_FEATURE_OFFHOTSPOT_SIMREFRESH = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_OFFHOTSPOT_SIMREFRESH);
        OPLUS_FEATURE_RADIO_LCMHOPPING_URC = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_RADIO_LCMHOPPING_URC);
        OPLUS_FEATURE_1X_BSR_DDS_SWITCH = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_1X_BSR_DDS_SWITCH);
        OPLUS_FEATURE_UST_5G_UC = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_UST_5G_UC);
        OPLUS_FEATURE_UST_ADB_SET_SVN = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.OPLUS_FEATURE_UST_ADB_SET_SVN);
        OPLUS_FEATURE_FIVE_SIGNAL_BAR = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_FIVE_SIGNAL_BAR);
        OPLUS_FEATURE_5G_BAND_CFG = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_5G_BAND_CFG);
        OPLUS_FEATURE_SAR_BACKOFF_DISABLED = OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SAR_BACKOFF_DISABLED);
        Rlog.d("OplusFeature init: ", "OPLUS_FEATURE_SIGNAL_SMOOTH = " + OPLUS_FEATURE_SIGNAL_SMOOTH + ", hasFeature =" + OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SIGNAL_SMOOTH_DISABLED) + ", OPLUS_FEATURE_NR_ICON_OPTIMIZED = " + OPLUS_FEATURE_NR_ICON_OPTIMIZED + ", OPLUS_FEATURE_FAST_RECOVERY = " + OPLUS_FEATURE_FAST_RECOVERY + ", FEATURE_NW_RADIO_HOOK = " + hasFeature);
    }

    public static boolean isMTKPlatform() {
        return isMTKPlatform;
    }

    public static boolean isQcomPlatform() {
        return isQcomPlatform;
    }

    public static boolean isDualNrEnabled() {
        if (OPLUS_FEATURE_SUPPORT_DUAL_NR) {
            return OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_DUAL_NR_ENABLED);
        }
        return false;
    }

    public static boolean isSilentRedialEnabled() {
        if (OPLUS_FEATURE_SILENT_REDIAL_SUPPORTED) {
            return OplusFeatureHelper.getInstance().hasFeature(IOplusFeatureConfigList.FEATURE_SILENT_REDIAL_ENABLED);
        }
        return false;
    }
}
